set_parameter:
  target:
  fields:
    device_id:
      required: true
      example: "12345"
      selector:
        text:
    model_index:
      required: true
      example: 1
      selector:
        number:
          min: 0
          max: 255
    parameter_index:
      required: true
      example: 10
      selector:
        number:
          min: 0
          max: 255
    value:
      required: true
      example: 100
      selector:
        number:
          min: 0
          max: 65535
